"""initial schema: policies, evidence, cases, runs, trace, jobs, audit (F02)

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 15:23:16.676586
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


APPEND_ONLY = '''
CREATE FUNCTION forbid_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION '% is append-only (% blocked)', TG_TABLE_NAME, TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$;
CREATE TRIGGER audit_events_append_only BEFORE UPDATE OR DELETE ON audit_events
  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
-- Reviews and run events may be removed with their case, but never edited.
CREATE TRIGGER reviews_no_update BEFORE UPDATE ON reviews
  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
CREATE TRIGGER run_events_no_update BEFORE UPDATE ON run_events
  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();
'''


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_org_time', 'audit_events', ['organization_id', 'occurred_at'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('business_area', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_cases_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_cases_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_index('ix_cases_org_updated', 'cases', ['organization_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_cases_owner_id'), 'cases', ['owner_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Enum('queued', 'running', 'succeeded', 'failed', name='job_state', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('queued', 'running', 'succeeded', 'failed')", name=op.f('ck_jobs_job_state')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_jobs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('job_type', 'idempotency_key', name=op.f('uq_jobs_job_type_idempotency_key'))
    )
    op.create_index('ix_jobs_claim', 'jobs', ['state', 'next_attempt_at'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('requester', 'reviewer', 'admin', name='role', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('requester', 'reviewer', 'admin')", name=op.f('ck_memberships_role')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id', name=op.f('pk_memberships'))
    )
    op.create_table('policies',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('business_area', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('applicability', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_policies_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_policies_organization_id_slug'))
    )
    op.create_index(op.f('ix_policies_organization_id'), 'policies', ['organization_id'], unique=False)
    op.create_table('policy_snapshots',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_policy_snapshots_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_snapshots'))
    )
    op.create_index(op.f('ix_policy_snapshots_organization_id'), 'policy_snapshots', ['organization_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.Text(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_uploads_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_uploads_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads')),
    sa.UniqueConstraint('organization_id', 'sha256', name=op.f('uq_uploads_organization_id_sha256'))
    )
    op.create_table('policy_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('policy_id', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'superseded', name='version_status', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('index_status', sa.Enum('indexing', 'ready', 'failed', name='index_status', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('index_revision', sa.Text(), nullable=True),
    sa.Column('original_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('upload_id', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingest_error', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("index_status IN ('indexing', 'ready', 'failed')", name=op.f('ck_policy_versions_index_status')),
    sa.CheckConstraint("status <> 'published' OR index_status = 'ready'", name=op.f('ck_policy_versions_published_is_indexed')),
    sa.CheckConstraint("status IN ('draft', 'published', 'superseded')", name=op.f('ck_policy_versions_version_status')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_policy_versions_effective_range')),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_policy_versions_policy_id_policies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_policy_versions_upload_id_uploads'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_versions')),
    sa.UniqueConstraint('policy_id', 'label', name=op.f('uq_policy_versions_policy_id_label'))
    )
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.create_table('scenario_revisions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('parent_revision_id', sa.Text(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('hypothetical', sa.Boolean(), nullable=False),
    sa.Column('changed_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmed_assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_scenario_revisions_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_scenario_revisions_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['scenario_revisions.id'], name=op.f('fk_scenario_revisions_parent_revision_id_scenario_revisions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_revisions')),
    sa.UniqueConstraint('case_id', 'revision_number', name=op.f('uq_scenario_revisions_case_id_revision_number'))
    )
    op.create_index(op.f('ix_scenario_revisions_case_id'), 'scenario_revisions', ['case_id'], unique=False)
    op.create_table('assessment_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('scenario_revision_id', sa.Text(), nullable=False),
    sa.Column('snapshot_id', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('queued', 'running', 'waiting_for_user', 'completed', 'failed', 'canceled', name='run_state', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('result_status', sa.Enum('non_compliant', 'conflicting_policy', 'insufficient_information', 'compliant_within_scope', 'out_of_scope', name='result_status', native_enum=False, create_constraint=False, length=32), nullable=True),
    sa.Column('review_state', sa.Enum('unreviewed', 'accepted', 'challenged', 'information_requested', name='review_state', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("result_status IN ('non_compliant', 'conflicting_policy', 'insufficient_information', 'compliant_within_scope', 'out_of_scope')", name=op.f('ck_assessment_runs_result_status')),
    sa.CheckConstraint("review_state IN ('unreviewed', 'accepted', 'challenged', 'information_requested')", name=op.f('ck_assessment_runs_review_state')),
    sa.CheckConstraint("state IN ('queued', 'running', 'waiting_for_user', 'completed', 'failed', 'canceled')", name=op.f('ck_assessment_runs_run_state')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_assessment_runs_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_assessment_runs_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assessment_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_revision_id'], ['scenario_revisions.id'], name=op.f('fk_assessment_runs_scenario_revision_id_scenario_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['policy_snapshots.id'], name=op.f('fk_assessment_runs_snapshot_id_policy_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_runs')),
    sa.UniqueConstraint('case_id', 'idempotency_key', name=op.f('uq_assessment_runs_case_id_idempotency_key'))
    )
    op.create_index(op.f('ix_assessment_runs_case_id'), 'assessment_runs', ['case_id'], unique=False)
    op.create_index('ix_assessment_runs_org_created', 'assessment_runs', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_assessment_runs_snapshot_id'), 'assessment_runs', ['snapshot_id'], unique=False)
    op.create_table('clauses',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('policy_version_id', sa.Text(), nullable=False),
    sa.Column('clause_key', sa.String(length=64), nullable=False),
    sa.Column('section_path', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('section_headings', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('definition', 'requirement', 'exception', 'general', name='clause_kind', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('extraction_quality', sa.Enum('ok', 'warning', 'low', name='extraction_quality', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.CheckConstraint("extraction_quality IN ('ok', 'warning', 'low')", name=op.f('ck_clauses_extraction_quality')),
    sa.CheckConstraint("kind IN ('definition', 'requirement', 'exception', 'general')", name=op.f('ck_clauses_clause_kind')),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], name=op.f('fk_clauses_policy_version_id_policy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clauses')),
    sa.UniqueConstraint('policy_version_id', 'clause_key', name=op.f('uq_clauses_policy_version_id_clause_key'))
    )
    op.create_index(op.f('ix_clauses_policy_version_id'), 'clauses', ['policy_version_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('policy_version_id', sa.Text(), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('page_label', sa.String(length=32), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], name=op.f('fk_document_pages_policy_version_id_policy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('policy_version_id', 'page_index', name=op.f('pk_document_pages'))
    )
    op.create_table('messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Text(), nullable=False),
    sa.Column('scenario_revision_id', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_messages_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_revision_id'], ['scenario_revisions.id'], name=op.f('fk_messages_scenario_revision_id_scenario_revisions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_case_id'), 'messages', ['case_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('policy_version_id', sa.Text(), nullable=False),
    sa.Column('requirement_key', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('modality', sa.Enum('must', 'must_not', 'may', name='modality', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('required_action', sa.Text(), nullable=False),
    sa.Column('exception_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_needed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_state', sa.Enum('proposed', 'reviewed', 'rejected', name='review_state', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("modality IN ('must', 'must_not', 'may')", name=op.f('ck_requirements_modality')),
    sa.CheckConstraint("review_state IN ('proposed', 'reviewed', 'rejected')", name=op.f('ck_requirements_review_state')),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], name=op.f('fk_requirements_policy_version_id_policy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements')),
    sa.UniqueConstraint('policy_version_id', 'requirement_key', name=op.f('uq_requirements_policy_version_id_requirement_key'))
    )
    op.create_index(op.f('ix_requirements_policy_version_id'), 'requirements', ['policy_version_id'], unique=False)
    op.create_table('snapshot_versions',
    sa.Column('snapshot_id', sa.Text(), nullable=False),
    sa.Column('policy_version_id', sa.Text(), nullable=False),
    sa.Column('index_revision', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], name=op.f('fk_snapshot_versions_policy_version_id_policy_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['policy_snapshots.id'], name=op.f('fk_snapshot_versions_snapshot_id_policy_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'policy_version_id', name=op.f('pk_snapshot_versions'))
    )
    op.create_index(op.f('ix_snapshot_versions_policy_version_id'), 'snapshot_versions', ['policy_version_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('sender', sa.Enum('retrieval', 'analysis', 'risk', 'validation', 'recommendation', name='sender', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('recipient', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('causal_parent_id', sa.Text(), nullable=True),
    sa.Column('remaining_repair_rounds', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=8), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sender IN ('retrieval', 'analysis', 'risk', 'validation', 'recommendation')", name=op.f('ck_agent_messages_sender')),
    sa.ForeignKeyConstraint(['causal_parent_id'], ['agent_messages.id'], name=op.f('fk_agent_messages_causal_parent_id_agent_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], name=op.f('fk_agent_messages_run_id_assessment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_messages'))
    )
    op.create_index(op.f('ix_agent_messages_run_id'), 'agent_messages', ['run_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('clause_id', sa.Text(), nullable=False),
    sa.Column('policy_version_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', prefix), 'A') || setweight(to_tsvector('english', text), 'B')", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], name=op.f('fk_chunks_clause_id_clauses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], name=op.f('fk_chunks_policy_version_id_policy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('clause_id', 'ordinal', name=op.f('uq_chunks_clause_id_ordinal'))
    )
    op.create_index(op.f('ix_chunks_clause_id'), 'chunks', ['clause_id'], unique=False)
    op.create_index(op.f('ix_chunks_policy_version_id'), 'chunks', ['policy_version_id'], unique=False)
    op.create_index('ix_chunks_search_vector', 'chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('clause_relations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_clause_id', sa.Text(), nullable=False),
    sa.Column('target_clause_id', sa.Text(), nullable=False),
    sa.Column('relation', sa.Enum('references', 'excepts', 'overrides', name='relation', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("relation IN ('references', 'excepts', 'overrides')", name=op.f('ck_clause_relations_relation')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_clause_relations_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_clause_id'], ['clauses.id'], name=op.f('fk_clause_relations_source_clause_id_clauses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_clause_id'], ['clauses.id'], name=op.f('fk_clause_relations_target_clause_id_clauses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clause_relations')),
    sa.UniqueConstraint('source_clause_id', 'target_clause_id', 'relation', name=op.f('uq_clause_relations_source_clause_id_target_clause_id_relation'))
    )
    op.create_index(op.f('ix_clause_relations_source_clause_id'), 'clause_relations', ['source_clause_id'], unique=False)
    op.create_index(op.f('ix_clause_relations_target_clause_id'), 'clause_relations', ['target_clause_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('scenario_revision_id', sa.Text(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('origin', sa.Enum('provided', 'inferred', 'unknown', name='origin', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('source_message_id', sa.Text(), nullable=True),
    sa.CheckConstraint("(origin = 'unknown') = (value IS NULL)", name=op.f('ck_facts_unknown_has_no_value')),
    sa.CheckConstraint("origin IN ('provided', 'inferred', 'unknown')", name=op.f('ck_facts_origin')),
    sa.ForeignKeyConstraint(['scenario_revision_id'], ['scenario_revisions.id'], name=op.f('fk_facts_scenario_revision_id_scenario_revisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], name=op.f('fk_facts_source_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facts')),
    sa.UniqueConstraint('scenario_revision_id', 'key', name=op.f('uq_facts_scenario_revision_id_key'))
    )
    op.create_index(op.f('ix_facts_scenario_revision_id'), 'facts', ['scenario_revision_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('requirement_id', sa.Text(), nullable=True),
    sa.Column('requirement_ref', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('met', 'violated', 'unknown', 'not_applicable', 'conflict', name='requirement_status', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('support', sa.Enum('validated', 'unsupported', 'contradicted', 'pending', name='support', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('missing_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("status IN ('met', 'violated', 'unknown', 'not_applicable', 'conflict')", name=op.f('ck_findings_requirement_status')),
    sa.CheckConstraint("support IN ('validated', 'unsupported', 'contradicted', 'pending')", name=op.f('ck_findings_support')),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_findings_requirement_id_requirements'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], name=op.f('fk_findings_run_id_assessment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index(op.f('ix_findings_run_id'), 'findings', ['run_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('suggested_role', sa.Text(), nullable=False),
    sa.Column('completion_criteria', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('mandatory', 'optional', name='recommendation_kind', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.CheckConstraint("kind IN ('mandatory', 'optional')", name=op.f('ck_recommendations_recommendation_kind')),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], name=op.f('fk_recommendations_run_id_assessment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_run_id'), 'recommendations', ['run_id'], unique=False)
    op.create_table('requirement_clauses',
    sa.Column('requirement_id', sa.Text(), nullable=False),
    sa.Column('clause_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], name=op.f('fk_requirement_clauses_clause_id_clauses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_requirement_clauses_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requirement_id', 'clause_id', name=op.f('pk_requirement_clauses'))
    )
    op.create_index(op.f('ix_requirement_clauses_clause_id'), 'requirement_clauses', ['clause_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('reviewer_id', sa.Text(), nullable=False),
    sa.Column('disposition', sa.Enum('accepted', 'challenged', 'information_requested', name='disposition', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("disposition IN ('accepted', 'challenged', 'information_requested')", name=op.f('ck_reviews_disposition')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], name=op.f('fk_reviews_run_id_assessment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_index(op.f('ix_reviews_run_id'), 'reviews', ['run_id'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severity', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('likelihood', sa.Enum('unknown', 'low', 'medium', 'high', name='likelihood', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rubric_version', sa.String(length=64), nullable=False),
    sa.CheckConstraint("likelihood IN ('unknown', 'low', 'medium', 'high')", name=op.f('ck_risks_likelihood')),
    sa.CheckConstraint("severity IN ('critical', 'high', 'medium', 'low')", name=op.f('ck_risks_severity')),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], name=op.f('fk_risks_run_id_assessment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risks'))
    )
    op.create_index(op.f('ix_risks_run_id'), 'risks', ['run_id'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=8), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], name=op.f('fk_run_events_run_id_assessment_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_events')),
    sa.UniqueConstraint('run_id', 'sequence', name=op.f('uq_run_events_run_id_sequence'))
    )
    op.create_table('source_spans',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('clause_id', sa.Text(), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('page_label', sa.String(length=32), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('text_start', sa.Integer(), nullable=False),
    sa.Column('text_end', sa.Integer(), nullable=False),
    sa.Column('bboxes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('char_end > char_start', name=op.f('ck_source_spans_nonempty')),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], name=op.f('fk_source_spans_clause_id_clauses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_spans')),
    sa.UniqueConstraint('clause_id', 'page_index', 'char_start', name=op.f('uq_source_spans_clause_id_page_index_char_start'))
    )
    op.create_index(op.f('ix_source_spans_clause_id'), 'source_spans', ['clause_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('policy_version_id', sa.Text(), nullable=False),
    sa.Column('clause_id', sa.Text(), nullable=False),
    sa.Column('span_id', sa.Text(), nullable=True),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('section_path', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('quote_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], name=op.f('fk_citations_clause_id_clauses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], name=op.f('fk_citations_policy_version_id_policy_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], name=op.f('fk_citations_run_id_assessment_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['span_id'], ['source_spans.id'], name=op.f('fk_citations_span_id_source_spans'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations'))
    )
    op.create_index(op.f('ix_citations_clause_id'), 'citations', ['clause_id'], unique=False)
    op.create_index(op.f('ix_citations_run_id'), 'citations', ['run_id'], unique=False)
    op.create_table('finding_facts',
    sa.Column('finding_id', sa.Text(), nullable=False),
    sa.Column('fact_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], name=op.f('fk_finding_facts_fact_id_facts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_facts_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', 'fact_id', name=op.f('pk_finding_facts'))
    )
    op.create_index(op.f('ix_finding_facts_fact_id'), 'finding_facts', ['fact_id'], unique=False)
    op.create_table('recommendation_findings',
    sa.Column('recommendation_id', sa.Text(), nullable=False),
    sa.Column('finding_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_recommendation_findings_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_findings_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id', 'finding_id', name=op.f('pk_recommendation_findings'))
    )
    op.create_index(op.f('ix_recommendation_findings_finding_id'), 'recommendation_findings', ['finding_id'], unique=False)
    op.create_table('risk_findings',
    sa.Column('risk_id', sa.Text(), nullable=False),
    sa.Column('finding_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_risk_findings_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], name=op.f('fk_risk_findings_risk_id_risks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('risk_id', 'finding_id', name=op.f('pk_risk_findings'))
    )
    op.create_index(op.f('ix_risk_findings_finding_id'), 'risk_findings', ['finding_id'], unique=False)
    op.create_table('finding_citations',
    sa.Column('finding_id', sa.Text(), nullable=False),
    sa.Column('citation_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], name=op.f('fk_finding_citations_citation_id_citations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_citations_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', 'citation_id', name=op.f('pk_finding_citations'))
    )
    op.create_index(op.f('ix_finding_citations_citation_id'), 'finding_citations', ['citation_id'], unique=False)
    op.create_table('recommendation_citations',
    sa.Column('recommendation_id', sa.Text(), nullable=False),
    sa.Column('citation_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], name=op.f('fk_recommendation_citations_citation_id_citations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_citations_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id', 'citation_id', name=op.f('pk_recommendation_citations'))
    )
    op.create_index(op.f('ix_recommendation_citations_citation_id'), 'recommendation_citations', ['citation_id'], unique=False)
    # ### end Alembic commands ###
    op.execute(APPEND_ONLY)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS run_events_no_update ON run_events")
    op.execute("DROP TRIGGER IF EXISTS reviews_no_update ON reviews")
    op.execute("DROP TRIGGER IF EXISTS audit_events_append_only ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS forbid_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_citations_citation_id'), table_name='recommendation_citations')
    op.drop_table('recommendation_citations')
    op.drop_index(op.f('ix_finding_citations_citation_id'), table_name='finding_citations')
    op.drop_table('finding_citations')
    op.drop_index(op.f('ix_risk_findings_finding_id'), table_name='risk_findings')
    op.drop_table('risk_findings')
    op.drop_index(op.f('ix_recommendation_findings_finding_id'), table_name='recommendation_findings')
    op.drop_table('recommendation_findings')
    op.drop_index(op.f('ix_finding_facts_fact_id'), table_name='finding_facts')
    op.drop_table('finding_facts')
    op.drop_index(op.f('ix_citations_run_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_clause_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_source_spans_clause_id'), table_name='source_spans')
    op.drop_table('source_spans')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_risks_run_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_reviews_run_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_requirement_clauses_clause_id'), table_name='requirement_clauses')
    op.drop_table('requirement_clauses')
    op.drop_index(op.f('ix_recommendations_run_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_findings_run_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_facts_scenario_revision_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_clause_relations_target_clause_id'), table_name='clause_relations')
    op.drop_index(op.f('ix_clause_relations_source_clause_id'), table_name='clause_relations')
    op.drop_table('clause_relations')
    op.drop_index('ix_chunks_search_vector', table_name='chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_chunks_policy_version_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_clause_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_agent_messages_run_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_snapshot_versions_policy_version_id'), table_name='snapshot_versions')
    op.drop_table('snapshot_versions')
    op.drop_index(op.f('ix_requirements_policy_version_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_messages_case_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_clauses_policy_version_id'), table_name='clauses')
    op.drop_table('clauses')
    op.drop_index(op.f('ix_assessment_runs_snapshot_id'), table_name='assessment_runs')
    op.drop_index('ix_assessment_runs_org_created', table_name='assessment_runs')
    op.drop_index(op.f('ix_assessment_runs_case_id'), table_name='assessment_runs')
    op.drop_table('assessment_runs')
    op.drop_index(op.f('ix_scenario_revisions_case_id'), table_name='scenario_revisions')
    op.drop_table('scenario_revisions')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_policy_snapshots_organization_id'), table_name='policy_snapshots')
    op.drop_table('policy_snapshots')
    op.drop_index(op.f('ix_policies_organization_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_table('memberships')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_cases_owner_id'), table_name='cases')
    op.drop_index('ix_cases_org_updated', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_audit_events_org_time', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
